#! /usr/bin/env bash
# Copyright Andrea Mancuso 2020 <andrea@fusilab.net>
#
## Very simple local check to show GitLab Runner status

if type gitlab-runner >/dev/null
  then
    _version=$(gitlab-runner --version 2>/dev/null | grep ^Version| awk '{print $2}')
    _runners=$(gitlab-runner list 2> >(grep Executor | wc -l ))
    _status=$(gitlab-runner status > /dev/null 2>&1 && echo 0 || echo 2)

    echo "$_status GitLab_Runner - Version: $_version, Runners: $_runners"
fi
