#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# Check_MK GitLab Runner Status plugin
#
# Copyright 2020, Andrea Mancuso <andrea@fusilab.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import json

def inventory_gitlab_runner(info):
    if info:
        return [(None, None)]

def check_gitlab_runner(item, params, info):
    perfdata = []
    state = 0

    if info:
        _runners = 0
        _runner_list = ""
        for line in info:
            key = str(line[0])
            if key == 'Version': _version = str(line[1])
            if key == 'Status': state = int(str(line[1]))
            line = " ".join(line)
            if line.startswith('{"'):
                log = json.loads(line)
                _runners += 1
                _runner_list += log['msg'] + " - "

        infotext = "Version: %s, Runners: %d - %s" % (_version, _runners, _runner_list[:-3] )
        perfdata = [("Runners", _runners)]

    yield state, infotext, perfdata

check_info["gitlab_runner"] = {
    'check_function':            check_gitlab_runner,
    'inventory_function':        inventory_gitlab_runner,
    'service_description':       'GitLab Runner',
    'has_perfdata':              True,
    'group':                     'gitlab',
}
